# Generated by Django 2.2.10 on 2020-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_historicalarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
