# Generated by Django 2.2.10 on 2020-05-21 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200521_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('(?=(^(.*?[\\w \\d \\s].*?){50,}$))(?=(^.{1,200}$))', message='Article cannot be longer than 200 characters and cannot have more than 150 symbols.')]),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('(?=(^(.*?[\\w \\d \\s].*?){50,}$))(?=(^.{1,200}$))', message='Article cannot be longer than 200 characters and cannot have more than 150 symbols.')]),
        ),
    ]
