# for backward compatibility in case future Docker
version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=cynoblogbase
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            # - POSTGRES_HOST=localhost
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db
    
# volumes is for synchronising code folder
