# Generated by Django 2.2.10 on 2020-05-21 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_historicalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[django.core.validators.RegexValidator('(?=.{32,})(?=.*[\\d\\w]+).*$', message='Needs at least 32 characters with at least one alphanumeric.')]),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='body',
            field=models.TextField(validators=[django.core.validators.RegexValidator('(?=.{32,})(?=.*[\\d\\w]+).*$', message='Needs at least 32 characters with at least one alphanumeric.')]),
        ),
    ]
